import { IProAthlete } from "./athletes"

export type IBoxScoreItem = {
    athlete_id: string,
    game_id: string,
    athlete: IProAthlete
    player_type: string,
    player_name: string,
    passes: number,
    carries: number,
    carriesmadegainline: number,
    linebreaks: number,
    defendersbeaten: number,
    offloads: number,
    tries: number,
    metres: number,
    tacklesmade: number,
    tacklesuccess: number,
    tacklesmissed: number,
    turnoverswon: number,
    lineoutswonsteal: number,
    lineoutswon: number,
    penaltiesconceded: number,
    yellowcards: number,
    redcards: number,
    turnoversconceded: number,
    kicksfromhand: number,
    kicksfromhandmetres: number,
    retainedkicks: number,
    trykicks: number,
    conversionsscored: number,
    conversionsmissed: number,
    penaltygoalsscored: number,
    dropgoalsscored: number,
    points: number,
    minutesplayed: number
}