export type IFixture = {
    game_id: string,
    team_score?: number,
    opposition_score?: number,
    venue?: string,
    kickoff_time?: Date,
    competition_name?: string,
    team_id: number,
    opposition_team_id: string,
    is_knockout?: boolean,
    is_league_managed?: boolean,
    location?: string,
    extra_info?: string,
    hidden?: boolean,
    league_id: string,
    network?: string,
    game_status?: string,
    game_clock?: string,
    result: string,
    source_id?: string,
    data_source?: string,
    is_test?: boolean,
    round: number,
    home_team: string,
    away_team: string
}