export type ICompetitionGame = {
    game_id: string,
    team_score?: number,
    opposition_score?: number,
    venue?: string,
    kickoff_time?: Date,
    competition_name?: string,
    team_id: string,
    opposition_team_id: string,
    is_knockout?: boolean,
    is_league_managed?: boolean,
    location?: string,
    extra_info: string,
    hidden?: false,
    league_id: string,
    network?: string,
    game_status?: string,
    game_clock?: string,
    result?: string,
    source_id?: string,
    data_source?: string,
    is_test?: boolean,
    round: number,
    team_name: string,
    team_image_url: string,
    opposition_team_name: string,
    opposition_team_image_url: string
}