declare module "lucide-react" {
  import { ComponentType } from "react";

  export interface IconProps {
    color?: string;
    size?: string | number;
    strokeWidth?: string | number;
    className?: string;
  }

  type CIP = ComponentType<IconProps>

  export const ChevronRight: ComponentType<IconProps>;
  export const ChevronLeft: ComponentType<IconProps>;
  export const Users: ComponentType<IconProps>;
  export const Trophy: ComponentType<IconProps>;
  export const Award: ComponentType<IconProps>;
  export const PlusCircle: ComponentType<IconProps>;
  export const Loader: ComponentType<IconProps>;
  export const Search: ComponentType<IconProps>;
  export const Filter: ComponentType<IconProps>;
  export const X: ComponentType<IconProps>;
  export const Zap: ComponentType<IconProps>;
  export const Star: ComponentType<IconProps>;
  export const StarHalf: ComponentType<IconProps>;
  export const Plus: ComponentType<IconProps>;
  export const Mail: ComponentType<IconProps>;
  export const Eye: ComponentType<IconProps>;
  export const EyeOff: ComponentType<IconProps>;
  // Add other icons as needed
  export const Calendar: ComponentType<IconProps>;
  export const Shield: ComponentType<IconProps>;
  export const Minus: ComponentType<IconProps>;
  export const ArrowLeft: CIP;
  export const MapPin: CIP;
  export const Watch: CIP;
  export const RulerIcon: CIP;
  export const WeightIcon: CIP;
  export const Crosshair: CIP;
  export const RulerDimensionLineIcon: CIP;
  export const Target: CIP;
  export const Settings: CIP;
  export const HelpCircle: CIP;
  export const Share2: CIP;
  export const ArrowUp: CIP;
  export const ArrowDown: CIP;
  export const History: CIP;
  export const Lock: CIP;
  export const ArrowRight: CIP;
  export const User: CIP;
  export const Flag: CIP;
  export const ArrowDownRightIcon: CIP;
  export const FlameIcon: CIP;
  export const MinusIcon: CIP;
  export const Check: CIP;
  export const ChevronDown: CIP;
  export const Edit2: CIP;
  export const LogOut: CIP;
  export const Moon: CIP;
  export const Bell: CIP;
  export const Medal: CIP;
  export const Check: CIP;
  export const Info: CIP;
  export const Bomb: CIP;
  export const Copy: CIP;
  export const PlayCircleIcon: CIP;
  export const WatchIcon: CIP;
  export const Coins: CIP;
  export const CoinsIcon: CIP;
  export const CircleDollarSign: CIP;
  export const Menu: CIP;
  export const Pencil: CIP;
  export const Dot: CIP;
  export const Unlock: CIP;
  export const CircleXIcon: CIP;
  export const PercentIcon: CIP;
  export const BarChart: CIP;
  export const Home: CIP;
  export const School2: CIP;
  export const MessageCircle: CIP;
  export const CircleCheck: CIP;
  export const XIcon: CIP;
  export const FileX2: CIP;
  export const ChevronUp: CIP;
  export const LoaderCircle: CIP;
  export const Sparkles: CIP;
  export const Swords: CIP;
  export const Percent: CIP;
  export const XCircle: CIP;
  export const BowArrow: CIP;
  export const AlertCircle: CIP;
  export const ArrowUpDown: CIP;
  export const UserCircle: CIP;
  export const ChartNoAxesColumn: CIP;
  export const PlayCircle: CIP;
  export const Minimize2: CIP;
  export const Maximize2: CIP;
  export const Infinity: CIP;
  export const ArrowDownUp: CIP;
  export const Newspaper: CIP;
  export const ArrowLeftRight: CIP;
  export const Gem : CIP;
  export const Baby : CIP;
  export const BicepsFlexed : CIP;
  export const Dumbbell : CIP;
  export const WandSparkles : CIP;
  export const BadgeDollarSign : CIP;
  export const BrickWall : CIP;
  export const WifiOff : CIP;
  export const CheckCircle2 : CIP;
  export const DollarSign : CIP;
  export const Globe : CIP;
  export const Badge : CIP;
  export const Table2 : CIP;
  export const Hash : CIP;
  export const UserCog2 : CIP;
  export const Binoculars : CIP;
  export const Activity : CIP;
  export const CircleUserRound : CIP;
  export const BadgeCheck : CIP;
  export const KeyRound : CIP;
  export const FlaskConical : CIP;
  export const Table : CIP;
  export const Tv : CIP;
  export const Video : CIP;
  export const BadgeInfo : CIP;
  export const TriangleAlert : CIP;
  export const BellDot : CIP;
  export const PauseCircle : CIP;
  export const ChevronsUpDown : CIP;
  export const Repeat : CIP;
  export const Sun : CIP;
  export const Ruler : CIP;
}

